name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        pnpm:
          - 7.18.1
        node: [14]

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.18.1
          run_install: false

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
        
      - name: Install dependencies
        run: pnpm install

      - name: Generate
        run: cd packages/client && npm run generate && npm run deploy
