name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        pnpm:
          - 7.18.1
        node: [14]

    steps:
      - uses: actions/checkout@v3
      
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
          
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.18.1
          run_install: false

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
        
      - name: Install dependencies
        run: pnpm install

      - name: Generate
        run: cd packages/client && npm run generate
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/client/dist
